affinity: {}
autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
fullnameOverride: ""
image:
    pullPolicy: IfNotPresent
    repositoryAPI: 021437093814.dkr.ecr.eu-north-1.amazonaws.com/api
    repositoryDashboard: 021437093814.dkr.ecr.eu-north-1.amazonaws.com/dashboard
    repositoryParser: 021437093814.dkr.ecr.eu-north-1.amazonaws.com/parser
    repositoryRabbitMQ: 021437093814.dkr.ecr.eu-north-1.amazonaws.com/rabbitmq-link
    tag: latest
imagePullSecrets: []
ingress:
    annotations: {}
    enabled: false
    hosts:
        - host: chart-example.local
          paths: []
    tls: []
keycloakAPIClientSecret: ""
keycloakServerUrl: https://keycloak.linkvisualizer.com
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
postgresHost: generalledger-demo.cydtuvgo2ulx.eu-north-1.rds.amazonaws.com
postgresPassword: XXU2QHprWTJwMDgzRVpbPm5tKEg=
postgresUser: dGVzdG5hbWUzMzM=
replicaCount: 1
resources: {}
securityContext: {}
service:
    port: 80
    type: ClusterIP
serviceAccount:
    annotations: {}
    create: true
    name: ""
tenantDomain: linkvisualizer.com
tenantName: testname333
tolerations: []
